# Generated by Django 4.1.7 on 2023-05-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_messenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisheraccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publisheraccount',
            name='bank_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='publisheraccount',
            name='bank_country',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='publisheraccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publisheraccount',
            name='custom',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='publisheraccount',
            name='usdt_trc',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='publisheraccount',
            name='wire_comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publisheraccount',
            name='wire_swift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
